# POST http://localhost:3000/api/girl/add
# Content-Type: application/json

# {
#     "id":4,
#     "name":"大梨",
#     "age":30
# }


# Get http://localhost:3000/api/girl/getGirlById?id=1

# Get http://localhost:3000/api/girl/2

# GET http://localhost:3000/api/girl/delete/4

# GET http://localhost:3000/api/girl/update/2

# GET http://localhost:3000/api/girl

GET http://localhost:3000/api/girl/findGirlByName/丫